stages:
  - test
  - build

before_script:
  - apt-get update && apt-get -yy install make

test:
  image: "cangol/android-gradle"
  script:
    - make test
  stage: test
  allow_failure: true

android:
  image: "cangol/android-gradle"
  before_script:
    - apt-get update && apt-get -yy install make
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-23"
  script:
    - make build-android
    - mv android/build/outputs/apk/*.apk .
  stage: build
  artifacts:
    paths:
      - "*.apk"

desktop:
  image: "cangol/android-gradle"
  script:
    - make build-desktop
    - mv desktop/build/libs/*.jar .
  stage: build
  artifacts:
    paths:
      - "*.jar"
